## Convolución Circular
### Mariana Noreña Vásquez
### CC 1000411870

## Librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings("ignore")

%matplotlib inline

$$x_{1}(n)=[\vec{2},4,6]$$
$$x_{2}(n)=[\vec{-1},0,1]$$

In [2]:
x1 = [2,4,6]
x2 = [-1,0,1]

X1 = np.fft.fft(x1)
X2 = np.fft.fft(x2)

conv = np.real(np.fft.ifft(X1*X2))
print(conv)

[ 2.  2. -4.]


- Se observa que la longitud de la convolución circular corresponde a la longitud mayor de ambas secuencias, la cual, en este caso es 3.

- Si en dado caso, las secuencias tuvieran longitud diferente, la de menor longitud se completa con ceros hasta tener la longitud de la secuencia mayor

$$x_{1}(n)=[\vec{5},3,0]$$
$$x_{2}(n)=[\vec{-3},-1,0,2]$$

In [3]:
x1 = np.array([5,3,0])
x2 = np.array([-3,-1,0,2])

if len(x1) < len(x2):
    x1 = np.concatenate((x1,np.zeros(len(x2)-len(x1))), axis=0)
elif len(x1) > len(x2):
    x2 = np.concatenate((x2,np.zeros(len(x1)-len(x2))), axis=0)

print(x1)
print(x2)

[5. 3. 0. 0.]
[-3 -1  0  2]


In [4]:
X1 = np.fft.fft(x1)
X2 = np.fft.fft(x2)

conv = np.real(np.fft.ifft(X1*X2))
print(conv)

[ -9. -14.  -3.  10.]
